---
name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Unit Tests
        run: dotnet test MillionThings.Tests
      - name: Integration Tests
        run: dotnet test MillionThings.IntegrationTests
